AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

ClassAndModuleChildren:
  Enabled: false

LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Alias:
  Enabled: false

Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '()'
    '%i': '()'

Metrics/MethodLength:
  Max: 15
