# TODO: Simplify this
version: 2
jobs:
  postgres_10:
    working_directory: ~/tablature-rb
    docker:
      - image: circleci/ruby:2.4
        environment:
          DATABASE_URL: "postgres://postgres@localhost:5432/dummy_test"
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: dummy_test
          POSTGRES_PASSWORD: ""
    steps:
      - run:
          name: "ok"
          command: echo "ok"


workflows:
  version: 2
  tablature:
    jobs:
      - postgres_10
