name: CI

on:
  push:
    branches: master
  pull_request:
    branches: "*"

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}, Postgres ${{ matrix.postgres }}

    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.4", "2.7"]
        rails: ["5.2", "6.0", "master"]
        postgres: ["10.12", "11.7", "12.2"]

        exclude:
          - ruby: "2.4"
            rails: "6.0"
          - ruby: "2.4"
            rails: "master"
        include:
          - postgres: "10.12"
            rspec_tag: --tag ~postgres_11
          - rails: "master"
            continue-on-error: true

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}-alpine
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      RAILS_VERSION: ${{ matrix.rails }}
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      CI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1.31.0
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Generate lockfile
        run: bundle lock

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('Gemfile.lock') }}

      - name: Set up Tablature
        run: bin/setup

      - name: Run tests
        run: bundle exec rspec ${{ matrix.rspec_tag }}
        continue-on-error: ${{ matrix.continue-on-error }}
